name: Build miyadaiku

on: 
  push:
  schedule:
    - cron:  '5 */8 * * *'
  workflow_dispatch:

jobs:
  workflow-keepalive:
    name: Re-enable workflow
#    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN || github.token }}
    steps:
      - run: |
          case "${GITHUB_WORKFLOW_REF:?}" in
            "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
            *) false ;;
          esac
          workflow="${GITHUB_WORKFLOW_REF%%@*}"
          workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
          gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"

  build:
    name: build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: where?
        run: |
          pwd

      - name: Create venv
        run: |
          python3 -m venv .venv


      - name: Install dependencies
        run: |
          .venv/bin/python -m pip install --upgrade pip wheel
          .venv/bin/pip3 install -r requirements.txt

      - name: Fetch python.org
        run: |
          .venv/bin/python get_releases.py > contents/python_releases.yml

      - name: build miyadaiku(release)
        run: |
          .venv/bin/miyadaiku-build -d site_url=https://pythonlinks.python.jp/ .
          sed -i.bak  "s/LAST_UPDATED/$(date)/g" outputs/ja/index.html
          sed -i.bak  "s/LAST_UPDATED/$(date)/g" outputs/en/index.html

      - name: copy files
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_DRAFT_PYTHON_JP}}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          cd outputs
          tar cjf gen.tjz *
          scp -i ../private_key -o StrictHostKeyChecking=no -P 13855 gen.tjz "draft@www.python.jp:/home/pythonlinks"
          ssh -i ../private_key  -o StrictHostKeyChecking=no -p 13855 draft@www.python.jp "cd /home/pythonlinks; tar xjmf gen.tjz --no-overwrite-dir"
          cd ..
          rm private_key

      - name: push changes
        run: |
          git config --global user.name 'github actions'
          git config --global user.email 'pythonlinks@users.noreply.github.com'
          git commit -am "Python releases updated" || true
          git push || true
          

